#!/bin/sh
python -m pushtotalk -i /home/mstts//Documents/Samples/1.wav -o /home/mstts//Documents/Samples/GHome24/1o.wav
python -m pushtotalk -i /home/mstts//Documents/Samples/2.wav -o /home/mstts//Documents/Samples/GHome24/2o.wav
python -m pushtotalk -i /home/mstts//Documents/Samples/3.wav -o /home/mstts//Documents/Samples/GHome24/3o.wav
python -m pushtotalk -i /home/mstts//Documents/Samples/4.wav -o /home/mstts//Documents/Samples/GHome24/4o.wav
python -m pushtotalk -i /home/mstts//Documents/Samples/5.wav -o /home/mstts//Documents/Samples/GHome24/5o.wav
python -m pushtotalk -i /home/mstts//Documents/Samples/6.wav -o /home/mstts//Documents/Samples/GHome24/6o.wav
python -m pushtotalk -i /home/mstts//Documents/Samples/7.wav -o /home/mstts//Documents/Samples/GHome24/7o.wav
python -m pushtotalk -i /home/mstts//Documents/Samples/8.wav -o /home/mstts//Documents/Samples/GHome24/8o.wav
python -m pushtotalk -i /home/mstts//Documents/Samples/9.wav -o /home/mstts//Documents/Samples/GHome24/9o.wav
python -m pushtotalk -i /home/mstts//Documents/Samples/10.wav -o /home/mstts//Documents/Samples/GHome24/10o.wav
python -m pushtotalk -i /home/mstts//Documents/Samples/11.wav -o /home/mstts//Documents/Samples/GHome24/11o.wav
python -m pushtotalk -i /home/mstts//Documents/Samples/12.wav -o /home/mstts//Documents/Samples/GHome24/12o.wav
python -m pushtotalk -i /home/mstts//Documents/Samples/13.wav -o /home/mstts//Documents/Samples/GHome24/13o.wav
python -m pushtotalk -i /home/mstts//Documents/Samples/14.wav -o /home/mstts//Documents/Samples/GHome24/14o.wav
python -m pushtotalk -i /home/mstts//Documents/Samples/15.wav -o /home/mstts//Documents/Samples/GHome24/15o.wav
python -m pushtotalk -i /home/mstts//Documents/Samples/16.wav -o /home/mstts//Documents/Samples/GHome24/16o.wav
python -m pushtotalk -i /home/mstts//Documents/Samples/17.wav -o /home/mstts//Documents/Samples/GHome24/17o.wav
python -m pushtotalk -i /home/mstts//Documents/Samples/18.wav -o /home/mstts//Documents/Samples/GHome24/18o.wav
python -m pushtotalk -i /home/mstts//Documents/Samples/19.wav -o /home/mstts//Documents/Samples/GHome24/19o.wav
python -m pushtotalk -i /home/mstts//Documents/Samples/20.wav -o /home/mstts//Documents/Samples/GHome24/20o.wav
python -m pushtotalk -i /home/mstts//Documents/Samples/21.wav -o /home/mstts//Documents/Samples/GHome24/21o.wav
python -m pushtotalk -i /home/mstts//Documents/Samples/22.wav -o /home/mstts//Documents/Samples/GHome24/22o.wav
python -m pushtotalk -i /home/mstts//Documents/Samples/23.wav -o /home/mstts//Documents/Samples/GHome24/23o.wav
python -m pushtotalk -i /home/mstts//Documents/Samples/24.wav -o /home/mstts//Documents/Samples/GHome24/24o.wav
python -m pushtotalk -i /home/mstts//Documents/Samples/25.wav -o /home/mstts//Documents/Samples/GHome24/25o.wav
python -m pushtotalk -i /home/mstts//Documents/Samples/26.wav -o /home/mstts//Documents/Samples/GHome24/26o.wav
python -m pushtotalk -i /home/mstts//Documents/Samples/27.wav -o /home/mstts//Documents/Samples/GHome24/27o.wav
python -m pushtotalk -i /home/mstts//Documents/Samples/28.wav -o /home/mstts//Documents/Samples/GHome24/28o.wav
python -m pushtotalk -i /home/mstts//Documents/Samples/29.wav -o /home/mstts//Documents/Samples/GHome24/29o.wav
python -m pushtotalk -i /home/mstts//Documents/Samples/30.wav -o /home/mstts//Documents/Samples/GHome24/30o.wav
python -m pushtotalk -i /home/mstts//Documents/Samples/31.wav -o /home/mstts//Documents/Samples/GHome24/31o.wav
python -m pushtotalk -i /home/mstts//Documents/Samples/32.wav -o /home/mstts//Documents/Samples/GHome24/32o.wav
python -m pushtotalk -i /home/mstts//Documents/Samples/33.wav -o /home/mstts//Documents/Samples/GHome24/33o.wav
python -m pushtotalk -i /home/mstts//Documents/Samples/34.wav -o /home/mstts//Documents/Samples/GHome24/34o.wav
python -m pushtotalk -i /home/mstts//Documents/Samples/35.wav -o /home/mstts//Documents/Samples/GHome24/35o.wav
python -m pushtotalk -i /home/mstts//Documents/Samples/36.wav -o /home/mstts//Documents/Samples/GHome24/36o.wav
python -m pushtotalk -i /home/mstts//Documents/Samples/37.wav -o /home/mstts//Documents/Samples/GHome24/37o.wav
python -m pushtotalk -i /home/mstts//Documents/Samples/38.wav -o /home/mstts//Documents/Samples/GHome24/38o.wav
python -m pushtotalk -i /home/mstts//Documents/Samples/39.wav -o /home/mstts//Documents/Samples/GHome24/39o.wav
python -m pushtotalk -i /home/mstts//Documents/Samples/40.wav -o /home/mstts//Documents/Samples/GHome24/40o.wav
python -m pushtotalk -i /home/mstts//Documents/Samples/41.wav -o /home/mstts//Documents/Samples/GHome24/41o.wav
python -m pushtotalk -i /home/mstts//Documents/Samples/42.wav -o /home/mstts//Documents/Samples/GHome24/42o.wav
python -m pushtotalk -i /home/mstts//Documents/Samples/43.wav -o /home/mstts//Documents/Samples/GHome24/43o.wav
python -m pushtotalk -i /home/mstts//Documents/Samples/44.wav -o /home/mstts//Documents/Samples/GHome24/44o.wav
python -m pushtotalk -i /home/mstts//Documents/Samples/45.wav -o /home/mstts//Documents/Samples/GHome24/45o.wav
python -m pushtotalk -i /home/mstts//Documents/Samples/46.wav -o /home/mstts//Documents/Samples/GHome24/46o.wav
python -m pushtotalk -i /home/mstts//Documents/Samples/47.wav -o /home/mstts//Documents/Samples/GHome24/47o.wav
python -m pushtotalk -i /home/mstts//Documents/Samples/48.wav -o /home/mstts//Documents/Samples/GHome24/48o.wav
python -m pushtotalk -i /home/mstts//Documents/Samples/49.wav -o /home/mstts//Documents/Samples/GHome24/49o.wav
python -m pushtotalk -i /home/mstts//Documents/Samples/50.wav -o /home/mstts//Documents/Samples/GHome24/50o.wav
python -m pushtotalk -i /home/mstts//Documents/Samples/51.wav -o /home/mstts//Documents/Samples/GHome24/51o.wav
python -m pushtotalk -i /home/mstts//Documents/Samples/52.wav -o /home/mstts//Documents/Samples/GHome24/52o.wav
python -m pushtotalk -i /home/mstts//Documents/Samples/53.wav -o /home/mstts//Documents/Samples/GHome24/53o.wav
python -m pushtotalk -i /home/mstts//Documents/Samples/54.wav -o /home/mstts//Documents/Samples/GHome24/54o.wav
python -m pushtotalk -i /home/mstts//Documents/Samples/55.wav -o /home/mstts//Documents/Samples/GHome24/55o.wav
python -m pushtotalk -i /home/mstts//Documents/Samples/56.wav -o /home/mstts//Documents/Samples/GHome24/56o.wav
python -m pushtotalk -i /home/mstts//Documents/Samples/57.wav -o /home/mstts//Documents/Samples/GHome24/57o.wav
python -m pushtotalk -i /home/mstts//Documents/Samples/58.wav -o /home/mstts//Documents/Samples/GHome24/58o.wav
python -m pushtotalk -i /home/mstts//Documents/Samples/59.wav -o /home/mstts//Documents/Samples/GHome24/59o.wav
python -m pushtotalk -i /home/mstts//Documents/Samples/60.wav -o /home/mstts//Documents/Samples/GHome24/60o.wav
python -m pushtotalk -i /home/mstts//Documents/Samples/61.wav -o /home/mstts//Documents/Samples/GHome24/61o.wav
python -m pushtotalk -i /home/mstts//Documents/Samples/62.wav -o /home/mstts//Documents/Samples/GHome24/62o.wav
python -m pushtotalk -i /home/mstts//Documents/Samples/63.wav -o /home/mstts//Documents/Samples/GHome24/63o.wav
python -m pushtotalk -i /home/mstts//Documents/Samples/64.wav -o /home/mstts//Documents/Samples/GHome24/64o.wav
python -m pushtotalk -i /home/mstts//Documents/Samples/65.wav -o /home/mstts//Documents/Samples/GHome24/65o.wav
python -m pushtotalk -i /home/mstts//Documents/Samples/66.wav -o /home/mstts//Documents/Samples/GHome24/66o.wav
python -m pushtotalk -i /home/mstts//Documents/Samples/67.wav -o /home/mstts//Documents/Samples/GHome24/67o.wav
python -m pushtotalk -i /home/mstts//Documents/Samples/68.wav -o /home/mstts//Documents/Samples/GHome24/68o.wav
python -m pushtotalk -i /home/mstts//Documents/Samples/69.wav -o /home/mstts//Documents/Samples/GHome24/69o.wav
python -m pushtotalk -i /home/mstts//Documents/Samples/70.wav -o /home/mstts//Documents/Samples/GHome24/70o.wav
python -m pushtotalk -i /home/mstts//Documents/Samples/71.wav -o /home/mstts//Documents/Samples/GHome24/71o.wav
python -m pushtotalk -i /home/mstts//Documents/Samples/72.wav -o /home/mstts//Documents/Samples/GHome24/72o.wav
python -m pushtotalk -i /home/mstts//Documents/Samples/73.wav -o /home/mstts//Documents/Samples/GHome24/73o.wav
python -m pushtotalk -i /home/mstts//Documents/Samples/74.wav -o /home/mstts//Documents/Samples/GHome24/74o.wav
python -m pushtotalk -i /home/mstts//Documents/Samples/75.wav -o /home/mstts//Documents/Samples/GHome24/75o.wav
python -m pushtotalk -i /home/mstts//Documents/Samples/76.wav -o /home/mstts//Documents/Samples/GHome24/76o.wav
python -m pushtotalk -i /home/mstts//Documents/Samples/77.wav -o /home/mstts//Documents/Samples/GHome24/77o.wav
python -m pushtotalk -i /home/mstts//Documents/Samples/78.wav -o /home/mstts//Documents/Samples/GHome24/78o.wav
python -m pushtotalk -i /home/mstts//Documents/Samples/79.wav -o /home/mstts//Documents/Samples/GHome24/79o.wav
python -m pushtotalk -i /home/mstts//Documents/Samples/80.wav -o /home/mstts//Documents/Samples/GHome24/80o.wav
python -m pushtotalk -i /home/mstts//Documents/Samples/81.wav -o /home/mstts//Documents/Samples/GHome24/81o.wav
python -m pushtotalk -i /home/mstts//Documents/Samples/82.wav -o /home/mstts//Documents/Samples/GHome24/82o.wav
python -m pushtotalk -i /home/mstts//Documents/Samples/83.wav -o /home/mstts//Documents/Samples/GHome24/83o.wav
python -m pushtotalk -i /home/mstts//Documents/Samples/84.wav -o /home/mstts//Documents/Samples/GHome24/84o.wav
python -m pushtotalk -i /home/mstts//Documents/Samples/85.wav -o /home/mstts//Documents/Samples/GHome24/85o.wav
python -m pushtotalk -i /home/mstts//Documents/Samples/86.wav -o /home/mstts//Documents/Samples/GHome24/86o.wav
python -m pushtotalk -i /home/mstts//Documents/Samples/87.wav -o /home/mstts//Documents/Samples/GHome24/87o.wav
python -m pushtotalk -i /home/mstts//Documents/Samples/88.wav -o /home/mstts//Documents/Samples/GHome24/88o.wav
python -m pushtotalk -i /home/mstts//Documents/Samples/89.wav -o /home/mstts//Documents/Samples/GHome24/89o.wav
python -m pushtotalk -i /home/mstts//Documents/Samples/90.wav -o /home/mstts//Documents/Samples/GHome24/90o.wav
python -m pushtotalk -i /home/mstts//Documents/Samples/91.wav -o /home/mstts//Documents/Samples/GHome24/91o.wav
python -m pushtotalk -i /home/mstts//Documents/Samples/92.wav -o /home/mstts//Documents/Samples/GHome24/92o.wav
python -m pushtotalk -i /home/mstts//Documents/Samples/93.wav -o /home/mstts//Documents/Samples/GHome24/93o.wav
python -m pushtotalk -i /home/mstts//Documents/Samples/94.wav -o /home/mstts//Documents/Samples/GHome24/94o.wav
python -m pushtotalk -i /home/mstts//Documents/Samples/95.wav -o /home/mstts//Documents/Samples/GHome24/95o.wav
python -m pushtotalk -i /home/mstts//Documents/Samples/96.wav -o /home/mstts//Documents/Samples/GHome24/96o.wav
python -m pushtotalk -i /home/mstts//Documents/Samples/97.wav -o /home/mstts//Documents/Samples/GHome24/97o.wav
python -m pushtotalk -i /home/mstts//Documents/Samples/98.wav -o /home/mstts//Documents/Samples/GHome24/98o.wav
python -m pushtotalk -i /home/mstts//Documents/Samples/99.wav -o /home/mstts//Documents/Samples/GHome24/99o.wav
python -m pushtotalk -i /home/mstts//Documents/Samples/100.wav -o /home/mstts//Documents/Samples/GHome24/100o.wav
